package com.lanou3g.gifttheory.util.dbtool;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lanou3g.gifttheory.util.dbtool.Collect;
import com.lanou3g.gifttheory.util.dbtool.Search;

import com.lanou3g.gifttheory.util.dbtool.CollectDao;
import com.lanou3g.gifttheory.util.dbtool.SearchDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectDaoConfig;
    private final DaoConfig searchDaoConfig;

    private final CollectDao collectDao;
    private final SearchDao searchDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectDaoConfig = daoConfigMap.get(CollectDao.class).clone();
        collectDaoConfig.initIdentityScope(type);

        searchDaoConfig = daoConfigMap.get(SearchDao.class).clone();
        searchDaoConfig.initIdentityScope(type);

        collectDao = new CollectDao(collectDaoConfig, this);
        searchDao = new SearchDao(searchDaoConfig, this);

        registerDao(Collect.class, collectDao);
        registerDao(Search.class, searchDao);
    }
    
    public void clear() {
        collectDaoConfig.clearIdentityScope();
        searchDaoConfig.clearIdentityScope();
    }

    public CollectDao getCollectDao() {
        return collectDao;
    }

    public SearchDao getSearchDao() {
        return searchDao;
    }

}
